/** 
 * Design tokens extracted from the Stitch export.
 * Keep this as the single source of truth for colors/spacing/type —
 * every new Stitch screen you bring in should be checked against this
 * file rather than letting each page invent its own values.
 */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#0f6b4c",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#161c27",
        "inverse-on-surface": "#f1f1ef",
        "on-background": "#1a1c1b",
        "error-container": "#ffdad6",
        "secondary-container": "#fdbf40",
        "on-primary-fixed": "#002114",
        "on-error-container": "#93000a",
        tertiary: "#404654",
        "on-tertiary-container": "#d2d8e8",
        "on-primary-container": "#97e9c1",
        primary: "#005138",
        "tertiary-fixed-dim": "#c1c6d7",
        "on-secondary-fixed": "#271900",
        "primary-fixed-dim": "#86d7b1",
        "surface-container-high": "#e8e8e6",
        outline: "#6f7a73",
        "surface-tint": "#106b4c",
        "surface-bright": "#f9f9f7",
        "surface-container-low": "#f4f4f2",
        "on-secondary-container": "#6f4e00",
        "surface-dim": "#dadad8",
        "surface-variant": "#e2e3e1",
        "on-surface-variant": "#3f4943",
        "tertiary-fixed": "#dde2f3",
        "surface-container-highest": "#e2e3e1",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#005138",
        "on-secondary-fixed-variant": "#5e4200",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-container": "#585e6c",
        "surface-container": "#eeeeec",
        "secondary-fixed-dim": "#fabc3e",
        "inverse-primary": "#86d7b1",
        "outline-variant": "#bec9c1",
        "primary-fixed": "#a1f3cc",
        "on-tertiary-fixed-variant": "#414754",
        secondary: "#7c5800",
        "on-surface": "#1a1c1b",
        "secondary-fixed": "#ffdea8",
        "inverse-surface": "#2f3130",
        background: "#f9f9f7",
        "on-tertiary": "#ffffff",
        surface: "#f9f9f7",
        "on-error": "#ffffff",
        whatsapp: "#25D366",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "32px",
        "stack-sm": "8px",
        "margin-mobile": "20px",
        gutter: "24px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "stack-md": "16px",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "price-display": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "price-display": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
